export const ACTIONS_MENSAJES = {
  VACIAR: 'VACIAR_MENSAJES',
  BORRAR: 'BORRAR_MENSAJES',
  CREAR: 'CREAR_MENSAJES',
  LEER: 'LEER_MENSAJES',
  RECUPERAR_PRODUCTOS: 'RECUPERAR_PRODUCTOS'
}

export const ACTIONS_LOGIN = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT'
}